[project]
name = "cld-mmrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-documentintelligence>=1.0.2",
    "azure-core>=1.35.1",
    "azure-identity>=1.25.1",
    "azure-search-documents>=11.6.0",
    "boto3>=1.40.50",
    "colpali-engine>=0.3.8",
    "dotenv>=0.9.9",
    "einops>=0.8.1",
    "fastapi[standard]>=0.119.0",
    "httpx>=0.28.1",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "openai>=2.3.0",
    "pymupdf>=1.26.4",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
